### ISSUE TITLE
Comparison with existing packages

### ISSUE THREAD

**Issue by dandv** [fabiospampinato/html-entities-decode#1]
Hi, how is this package different form [established](https://github.com/mdevils/html-entities/issues/43) (millions of weekly downloads) HTML entity decoding packages on NPM?

If it's just a test package that should not be in NPM, that's fine, but it pollutes the search space. Maybe scope or unpublish it?

**Comment by fabiospampinato** [comment]
I don't quite remember now, but I think this package is slightly smaller and takes less time at startup.

**Comment by dandv** [comment]
Ok, that's interesting, a bunch of people were concerned about [the bundle size of `he`](https://github.com/mathiasbynens/he/issues/64), and [`entities` has a performance comparison](https://github.com/fb55/entities#performance).
